### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by MaxChanger**
Added two new articles based on existing categories.

In addition, there is an article: Spatial-Temporal Transformer for 3D Point Cloud Sequences [arxiv](https://arxiv.org/abs/2110.09783).
I hope @hehefan can help to add, you should be familiar than me with these various metric on test dataset.

### CODE REVIEW

**Comment by hehefan** [comment]
Hi,

Many thanks. The article added.

Best.

**Comment by MaxChanger** [comment]
@hehefan Hello, I have added two paper in my fork branch, and try to merge to your branch, if you accept this pull request.
But you seem to have ignored these two articles and closed the pull request? (you cloud see the differences in `Files Changed`)

```
| 4   | [LiDAR-based 4D Panoptic Segmentation via Dynamic Shifting Network](https://github.com/hongfz16/DS-Net)                                                      |    CVPR'21      |
| 11  | [Self-supervised Point Cloud Prediction Using 3D Spatio-temporal Convolutional Networks](https://github.com/PRBonn/point-cloud-prediction)  |    CoRL'21      |

```

**Comment by hehefan** [comment]
Hi,

Apologies.

The two papers merged. 

Thank you.

**Comment by MaxChanger** [comment]
@hehefan It doesn't matter, next time if there are related articles found, do you want me to put it in the issue or submit a pull request (and then you will check and merge).

**Comment by hehefan** [comment]
Hi, I prefer to issue. Thank you so much.

**Pull request closed without merging**
